version: "3"

services: 
    app:
      build: .
      container_name: app-ignite
      ports: 
        - 3333:3333
      depends_on:
        - db
      networks:
        - app-connect
     
    db:
      image: postgres
      container_name: db-ignite
      restart: always
      ports: 
        - 5432:5432
      environment: 
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
      networks:
        - app-connect

networks:   
    app-connect:    
        driver: bridge